Template._loginButtonsLoggedOutWithoutDropdown.replaces("_loginButtonsLoggedOutDropdown");
Template._loginButtonsLoggedOutWithoutDropdown.inheritsHelpersFrom("_loginButtonsLoggedOutDropdown");
Template._loginButtonsLoggedOutWithoutDropdown.inheritsEventsFrom("_loginButtonsLoggedOutDropdown");
